#!/bin/sh

echo "Is it morning? Please anwer yes or no"
read timeofday
if [ $timeofday = "yes" ]; then
echo "Good morning"
elif [ $timeofday = "no" ]; then
echo "Good afternoon"
else
echo "sorry,please enter yes or no"
exit 1
fi

exit 0
